/** Taxonomía de errores publicada en el contrato v1. Los clientes deciden por `code`, no por `message`. */
export enum CodigoError {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  REFRESH_REUSED = 'REFRESH_REUSED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  EMAIL_TAKEN = 'EMAIL_TAKEN',
  INVALID_ROLE = 'INVALID_ROLE',
  CATEGORY_EXISTS = 'CATEGORY_EXISTS',
  CATEGORY_IN_USE = 'CATEGORY_IN_USE',
  INVALID_IMAGE = 'INVALID_IMAGE',
  MEDIA_STORE_ERROR = 'MEDIA_STORE_ERROR',

  STOCK_INSUFFICIENT = 'STOCK_INSUFFICIENT',
  PRODUCT_UNAVAILABLE = 'PRODUCT_UNAVAILABLE',
  EMPTY_CART = 'EMPTY_CART',
  ADDRESS_REQUIRED = 'ADDRESS_REQUIRED',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  INVALID_TRANSITION = 'INVALID_TRANSITION',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',

  COUPON_INVALID = 'COUPON_INVALID',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  COUPON_EXHAUSTED = 'COUPON_EXHAUSTED',

  ALREADY_PAID = 'ALREADY_PAID',
  ORDER_NOT_PAYABLE = 'ORDER_NOT_PAYABLE',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',

  REVIEW_NOT_ALLOWED = 'REVIEW_NOT_ALLOWED',
  REVIEW_EXISTS = 'REVIEW_EXISTS',

  MODULE_DISABLED = 'MODULE_DISABLED',
}
