spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:minimalecommerce}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:app}
    password: ${MYSQL_PASSWORD:change-me}
  jpa:
    properties:
      hibernate:
        format_sql: true

app:
  seed: true
